name: car_payment
description: "How Much Car Can You Afford?"
publish_to: "none"
version: 1.0.0+1
flutter: { uses-material-design: true }
environment: { sdk: ">=3.3.4 <4.0.0" }
dependencies: { flutter: { sdk: flutter } }
dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^3.0.0
